# Production settings

baseurl: "/pipelines"
url: "https://aws-weave-ship-challenge.github.io"
deploy_doc_url_prefix: https://aws-weave-ship-challenge/pipelines
main_url_prefix: https://aws-weave-ship-challenge.github.io

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
